# Titanic Dataset ML Project
Dataset from Kaggle [Titanic Challenge]()

## Setup

### Import Packages

In [31]:
# Include tqdm for monitoring progress as things run
import matplotlib.pyplot as plt
import sklearn as sk
import pandas as pd
import numpy as np
import xgboost
import tqdm

## Dataset

### Import Data

In [5]:
# use pandas
DATA = pd.read_csv('data/train.csv')

In [13]:
DATA.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
y_train = DATA['Survived']
y_train

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [15]:
x_train = DATA.drop('Survived',axis=1)
x_train

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [16]:
x_train.dtypes

PassengerId      int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

### Clean Dataset Check

In [22]:
check_empties = []
for column in x_train.columns:
    tmp_list = [column, int(np.sum(x_train[column].isna()))]
    #print(column)
    #print(np.sum(x_train[column].isna()))
    check_empties.append(tmp_list)
print(check_empties)

[['PassengerId', 0], ['Pclass', 0], ['Name', 0], ['Sex', 0], ['Age', 177], ['SibSp', 0], ['Parch', 0], ['Ticket', 0], ['Fare', 0], ['Cabin', 687], ['Embarked', 2]]

In [27]:
category = 'Age'
for value in zip(x_train[category],x_train[category].isna()):
    print(value)
#print(enumerate(x_train['Cabin'].isna())

(22.0, False)
(38.0, False)
(26.0, False)
(35.0, False)
(35.0, False)
(nan, True)
(54.0, False)
(2.0, False)
(27.0, False)
(14.0, False)
(4.0, False)
(58.0, False)
(20.0, False)
(39.0, False)
(14.0, False)
(55.0, False)
(2.0, False)
(nan, True)
(31.0, False)
(nan, True)
(35.0, False)
(34.0, False)
(15.0, False)
(28.0, False)
(8.0, False)
(38.0, False)
(nan, True)
(19.0, False)
(nan, True)
(nan, True)
(40.0, False)
(nan, True)
(nan, True)
(66.0, False)
(28.0, False)
(42.0, False)
(nan, True)
(21.0, False)
(18.0, False)
(14.0, False)
(40.0, False)
(27.0, False)
(nan, True)
(3.0, False)
(19.0, False)
(nan, True)
(nan, True)
(nan, True)
(nan, True)
(18.0, False)
(7.0, False)
(21.0, False)
(49.0, False)
(29.0, False)
(65.0, False)
(nan, True)
(21.0, False)
(28.5, False)
(5.0, False)
(11.0, False)
(22.0, False)
(38.0, False)
(45.0, False)
(4.0, False)
(nan, True)
(nan, True)
(29.0, False)
(19.0, False)
(17.0, False)
(26.0, False)
(32.0, False)
(16.0, False)
(21.0, False)
(26.0, False)
(32.0, False)
(25.0, False)
(nan, True)
(nan, True)
(0.83, False)
(30.0, False)
(22.0, False)
(29.0, False)
(nan, True)
(28.0, False)
(17.0, False)
(33.0, False)
(16.0, False)
(nan, True)
(23.0, False)
(24.0, False)
(29.0, False)
(20.0, False)
(46.0, False)
(26.0, False)
(59.0, False)
(nan, True)
(71.0, False)
(23.0, False)
(34.0, False)
(34.0, False)
(28.0, False)
(nan, True)
(21.0, False)
(33.0, False)
(37.0, False)
(28.0, False)
(21.0, False)
(nan, True)
(38.0, False)
(nan, True)
(47.0, False)
(14.5, False)
(22.0, False)
(20.0, False)
(17.0, False)
(21.0, False)
(70.5, False)
(29.0, False)
(24.0, False)
(2.0, False)
(21.0, False)
(nan, True)
(32.5, False)
(32.5, False)
(54.0, False)
(12.0, False)
(nan, True)
(24.0, False)
(nan, True)
(45.0, False)
(33.0, False)
(20.0, False)
(47.0, False)
(29.0, False)
(25.0, False)
(23.0, False)
(19.0, False)
(37.0, False)
(16.0, False)
(24.0, False)
(nan, True)
(22.0, False)
(24.0, False)
(19.0, False)
(18.0, False)
(19.0, False)
(27.0, False)
(9.0, False)
(36.5, False)
(42.0, False)
(51.0, False)
(22.0, False)
(55.5, False)
(40.5, False)
(nan, True)
(51.0, False)
(16.0, False)
(30.0, False)
(nan, True)
(nan, True)
(44.0, False)
(40.0, False)
(26.0, False)
(17.0, False)
(1.0, False)
(9.0, False)
(nan, True)
(45.0, False)
(nan, True)
(28.0, False)
(61.0, False)
(4.0, False)
(1.0, False)
(21.0, False)
(56.0, False)
(18.0, False)
(nan, True)
(50.0, False)
(30.0, False)
(36.0, False)
(nan, True)
(nan, True)
(9.0, False)
(1.0, False)
(4.0, False)
(nan, True)
(nan, True)
(45.0, False)
(40.0, False)
(36.0, False)
(32.0, False)
(19.0, False)
(19.0, False)
(3.0, False)
(44.0, False)
(58.0, False)
(nan, True)
(42.0, False)
(nan, True)
(24.0, False)
(28.0, False)
(nan, True)
(34.0, False)
(45.5, False)
(18.0, False)
(2.0, False)
(32.0, False)
(26.0, False)
(16.0, False)
(40.0, False)
(24.0, False)
(35.0, False)
(22.0, False)
(30.0, False)
(nan, True)
(31.0, False)
(27.0, False)
(42.0, False)
(32.0, False)
(30.0, False)
(16.0, False)
(27.0, False)
(51.0, False)
(nan, True)
(38.0, False)
(22.0, False)
(19.0, False)
(20.5, False)
(18.0, False)
(nan, True)
(35.0, False)
(29.0, False)
(59.0, False)
(5.0, False)
(24.0, False)
(nan, True)
(44.0, False)
(8.0, False)
(19.0, False)
(33.0, False)
(nan, True)
(nan, True)
(29.0, False)
(22.0, False)
(30.0, False)
(44.0, False)
(25.0, False)
(24.0, False)
(37.0, False)
(54.0, False)
(nan, True)
(29.0, False)
(62.0, False)
(30.0, False)
(41.0, False)
(29.0, False)
(nan, True)
(30.0, False)
(35.0, False)
(50.0, False)
(nan, True)
(3.0, False)
(52.0, False)
(40.0, False)
(nan, True)
(36.0, False)
(16.0, False)
(25.0, False)
(58.0, False)
(35.0, False)
(nan, True)
(25.0, False)
(41.0, False)
(37.0, False)
(nan, True)
(63.0, False)
(45.0, False)
(nan, True)
(7.0, False)
(35.0, False)
(65.0, False)
(28.0, False)
(16.0, False)
(19.0, False)
(nan, True)
(33.0, False)
(30.0, False)
(22.0, False)
(42.0, False)
(22.0, False)
(26.0, False)
(19.0, False)
(36.0, False)
(24.0, False)
(24.0, False)
(nan, True)
(23.5, False)
(2.0, False)
(nan, True)
(50.0, False)
(nan, True)
(nan, True)
(19.0, False)
(nan, True)
(nan, True)
(0.92, False)
(nan, True)
(17.0, False)
(30.0, False)
(30.0, False)
(24.0, False)
(18.0, False)
(26.0, False)
(28.0, False)
(43.0, False)
(26.0, False)
(24.0, False)
(54.0, False)
(31.0, False)
(40.0, False)
(22.0, False)
(27.0, False)
(30.0, False)
(22.0, False)
(nan, True)
(36.0, False)
(61.0, False)
(36.0, False)
(31.0, False)
(16.0, False)
(nan, True)
(45.5, False)
(38.0, False)
(16.0, False)
(nan, True)
(nan, True)
(29.0, False)
(41.0, False)
(45.0, False)
(45.0, False)
(2.0, False)
(24.0, False)
(28.0, False)
(25.0, False)
(36.0, False)
(24.0, False)
(40.0, False)
(nan, True)
(3.0, False)
(42.0, False)
(23.0, False)
(nan, True)
(15.0, False)
(25.0, False)
(nan, True)
(28.0, False)
(22.0, False)
(38.0, False)
(nan, True)
(nan, True)
(40.0, False)
(29.0, False)
(45.0, False)
(35.0, False)
(nan, True)
(30.0, False)
(60.0, False)
(nan, True)
(nan, True)
(24.0, False)
(25.0, False)
(18.0, False)
(19.0, False)
(22.0, False)
(3.0, False)
(nan, True)
(22.0, False)
(27.0, False)
(20.0, False)
(19.0, False)
(42.0, False)
(1.0, False)
(32.0, False)
(35.0, False)
(nan, True)
(18.0, False)
(1.0, False)
(36.0, False)
(nan, True)
(17.0, False)
(36.0, False)
(21.0, False)
(28.0, False)
(23.0, False)
(24.0, False)
(22.0, False)
(31.0, False)
(46.0, False)
(23.0, False)
(28.0, False)
(39.0, False)
(26.0, False)
(21.0, False)
(28.0, False)
(20.0, False)
(34.0, False)
(51.0, False)
(3.0, False)
(21.0, False)
(nan, True)
(nan, True)
(nan, True)
(33.0, False)
(nan, True)
(44.0, False)
(nan, True)
(34.0, False)
(18.0, False)
(30.0, False)
(10.0, False)
(nan, True)
(21.0, False)
(29.0, False)
(28.0, False)
(18.0, False)
(nan, True)
(28.0, False)
(19.0, False)
(nan, True)
(32.0, False)
(28.0, False)
(nan, True)
(42.0, False)
(17.0, False)
(50.0, False)
(14.0, False)
(21.0, False)
(24.0, False)
(64.0, False)
(31.0, False)
(45.0, False)
(20.0, False)
(25.0, False)
(28.0, False)
(nan, True)
(4.0, False)
(13.0, False)
(34.0, False)
(5.0, False)
(52.0, False)
(36.0, False)
(nan, True)
(30.0, False)
(49.0, False)
(nan, True)
(29.0, False)
(65.0, False)
(nan, True)
(50.0, False)
(nan, True)
(48.0, False)
(34.0, False)
(47.0, False)
(48.0, False)
(nan, True)
(38.0, False)
(nan, True)
(56.0, False)
(nan, True)
(0.75, False)
(nan, True)
(38.0, False)
(33.0, False)
(23.0, False)
(22.0, False)
(nan, True)
(34.0, False)
(29.0, False)
(22.0, False)
(2.0, False)
(9.0, False)
(nan, True)
(50.0, False)
(63.0, False)
(25.0, False)
(nan, True)
(35.0, False)
(58.0, False)
(30.0, False)
(9.0, False)
(nan, True)
(21.0, False)
(55.0, False)
(71.0, False)
(21.0, False)
(nan, True)
(54.0, False)
(nan, True)
(25.0, False)
(24.0, False)
(17.0, False)
(21.0, False)
(nan, True)
(37.0, False)
(16.0, False)
(18.0, False)
(33.0, False)
(nan, True)
(28.0, False)
(26.0, False)
(29.0, False)
(nan, True)
(36.0, False)
(54.0, False)
(24.0, False)
(47.0, False)
(34.0, False)
(nan, True)
(36.0, False)
(32.0, False)
(30.0, False)
(22.0, False)
(nan, True)
(44.0, False)
(nan, True)
(40.5, False)
(50.0, False)
(nan, True)
(39.0, False)
(23.0, False)
(2.0, False)
(nan, True)
(17.0, False)
(nan, True)
(30.0, False)
(7.0, False)
(45.0, False)
(30.0, False)
(nan, True)
(22.0, False)
(36.0, False)
(9.0, False)
(11.0, False)
(32.0, False)
(50.0, False)
(64.0, False)
(19.0, False)
(nan, True)
(33.0, False)
(8.0, False)
(17.0, False)
(27.0, False)
(nan, True)
(22.0, False)
(22.0, False)
(62.0, False)
(48.0, False)
(nan, True)
(39.0, False)
(36.0, False)
(nan, True)
(40.0, False)
(28.0, False)
(nan, True)
(nan, True)
(24.0, False)
(19.0, False)
(29.0, False)
(nan, True)
(32.0, False)
(62.0, False)
(53.0, False)
(36.0, False)
(nan, True)
(16.0, False)
(19.0, False)
(34.0, False)
(39.0, False)
(nan, True)
(32.0, False)
(25.0, False)
(39.0, False)
(54.0, False)
(36.0, False)
(nan, True)
(18.0, False)
(47.0, False)
(60.0, False)
(22.0, False)
(nan, True)
(35.0, False)
(52.0, False)
(47.0, False)
(nan, True)
(37.0, False)
(36.0, False)
(nan, True)
(49.0, False)
(nan, True)
(49.0, False)
(24.0, False)
(nan, True)
(nan, True)
(44.0, False)
(35.0, False)
(36.0, False)
(30.0, False)
(27.0, False)
(22.0, False)
(40.0, False)
(39.0, False)
(nan, True)
(nan, True)
(nan, True)
(35.0, False)
(24.0, False)
(34.0, False)
(26.0, False)
(4.0, False)
(26.0, False)
(27.0, False)
(42.0, False)
(20.0, False)
(21.0, False)
(21.0, False)
(61.0, False)
(57.0, False)
(21.0, False)
(26.0, False)
(nan, True)
(80.0, False)
(51.0, False)
(32.0, False)
(nan, True)
(9.0, False)
(28.0, False)
(32.0, False)
(31.0, False)
(41.0, False)
(nan, True)
(20.0, False)
(24.0, False)
(2.0, False)
(nan, True)
(0.75, False)
(48.0, False)
(19.0, False)
(56.0, False)
(nan, True)
(23.0, False)
(nan, True)
(18.0, False)
(21.0, False)
(nan, True)
(18.0, False)
(24.0, False)
(nan, True)
(32.0, False)
(23.0, False)
(58.0, False)
(50.0, False)
(40.0, False)
(47.0, False)
(36.0, False)
(20.0, False)
(32.0, False)
(25.0, False)
(nan, True)
(43.0, False)
(nan, True)
(40.0, False)
(31.0, False)
(70.0, False)
(31.0, False)
(nan, True)
(18.0, False)
(24.5, False)
(18.0, False)
(43.0, False)
(36.0, False)
(nan, True)
(27.0, False)
(20.0, False)
(14.0, False)
(60.0, False)
(25.0, False)
(14.0, False)
(19.0, False)
(18.0, False)
(15.0, False)
(31.0, False)
(4.0, False)
(nan, True)
(25.0, False)
(60.0, False)
(52.0, False)
(44.0, False)
(nan, True)
(49.0, False)
(42.0, False)
(18.0, False)
(35.0, False)
(18.0, False)
(25.0, False)
(26.0, False)
(39.0, False)
(45.0, False)
(42.0, False)
(22.0, False)
(nan, True)
(24.0, False)
(nan, True)
(48.0, False)
(29.0, False)
(52.0, False)
(19.0, False)
(38.0, False)
(27.0, False)
(nan, True)
(33.0, False)
(6.0, False)
(17.0, False)
(34.0, False)
(50.0, False)
(27.0, False)
(20.0, False)
(30.0, False)
(nan, True)
(25.0, False)
(25.0, False)
(29.0, False)
(11.0, False)
(nan, True)
(23.0, False)
(23.0, False)
(28.5, False)
(48.0, False)
(35.0, False)
(nan, True)
(nan, True)
(nan, True)
(36.0, False)
(21.0, False)
(24.0, False)
(31.0, False)
(70.0, False)
(16.0, False)
(30.0, False)
(19.0, False)
(31.0, False)
(4.0, False)
(6.0, False)
(33.0, False)
(23.0, False)
(48.0, False)
(0.67, False)
(28.0, False)
(18.0, False)
(34.0, False)
(33.0, False)
(nan, True)
(41.0, False)
(20.0, False)
(36.0, False)
(16.0, False)
(51.0, False)
(nan, True)
(30.5, False)
(nan, True)
(32.0, False)
(24.0, False)
(48.0, False)
(57.0, False)
(nan, True)
(54.0, False)
(18.0, False)
(nan, True)
(5.0, False)
(nan, True)
(43.0, False)
(13.0, False)
(17.0, False)
(29.0, False)
(nan, True)
(25.0, False)
(25.0, False)
(18.0, False)
(8.0, False)
(1.0, False)
(46.0, False)
(nan, True)
(16.0, False)
(nan, True)
(nan, True)
(25.0, False)
(39.0, False)
(49.0, False)
(31.0, False)
(30.0, False)
(30.0, False)
(34.0, False)
(31.0, False)
(11.0, False)
(0.42, False)
(27.0, False)
(31.0, False)
(39.0, False)
(18.0, False)
(39.0, False)
(33.0, False)
(26.0, False)
(39.0, False)
(35.0, False)
(6.0, False)
(30.5, False)
(nan, True)
(23.0, False)
(31.0, False)
(43.0, False)
(10.0, False)
(52.0, False)
(27.0, False)
(38.0, False)
(27.0, False)
(2.0, False)
(nan, True)
(nan, True)
(1.0, False)
(nan, True)
(62.0, False)
(15.0, False)
(0.83, False)
(nan, True)
(23.0, False)
(18.0, False)
(39.0, False)
(21.0, False)
(nan, True)
(32.0, False)
(nan, True)
(20.0, False)
(16.0, False)
(30.0, False)
(34.5, False)
(17.0, False)
(42.0, False)
(nan, True)
(35.0, False)
(28.0, False)
(nan, True)
(4.0, False)
(74.0, False)
(9.0, False)
(16.0, False)
(44.0, False)
(18.0, False)
(45.0, False)
(51.0, False)
(24.0, False)
(nan, True)
(41.0, False)
(21.0, False)
(48.0, False)
(nan, True)
(24.0, False)
(42.0, False)
(27.0, False)
(31.0, False)
(nan, True)
(4.0, False)
(26.0, False)
(47.0, False)
(33.0, False)
(47.0, False)
(28.0, False)
(15.0, False)
(20.0, False)
(19.0, False)
(nan, True)
(56.0, False)
(25.0, False)
(33.0, False)
(22.0, False)
(28.0, False)
(25.0, False)
(39.0, False)
(27.0, False)
(19.0, False)
(nan, True)
(26.0, False)
(32.0, False)

### Imputing Values Required?

In [ ]:
# Kinda but we will skip for now, will just impute as missing

### Encoding Required?

In [ ]:
# Depends on the model used, not for RF/XGB

### Train Test Split

In [ ]:
# Not necessary, separate file given

### Imputing Values if Required

## Model

### Model Setup

In [ ]:
# Models used (Estimators dict / list)
# Use: Random Forest, XGBoost, LightGBM (Not the last one)
estimators = {
    #[name, model]
    ['random_forest',   sk.ensemble.RandomForestClassifier()],
    ['xgboost',         xgboost.XGBClassifier()], 
    }

NameError: name 'XGBClassifier' is not defined

### Training

In [ ]:
# model.fit(x_train,y_train)

### Initial Results

In [ ]:
# Visualized; accuracy, PR Curves, AUC table summary
# model.predict(x_test)
# sklearn.score(y_train,y_test)

## Optimization

### Optuna Objective

### Train & Validation Sets

### Optimize Against Validation Set

### Perfomance Versus Unoptimized

### Results