# Titanic Dataset ML Project
Dataset from Kaggle [Titanic Challenge](https://www.kaggle.com/competitions/titanic/data)

## Setup

### Import Packages

In [1]:
# Include tqdm for monitoring progress as things run
import matplotlib.pyplot as plt
import sklearn as sk
import pandas as pd
import numpy as np
import xgboost
import tqdm
import re

## Dataset

### Import Data

In [2]:
# use pandas
DATA = pd.read_csv('data/train.csv')

In [3]:
#print(DATA.head())
y_train = DATA['Survived']
#y_train

In [4]:
x_train = DATA.drop(['Survived','PassengerId','Ticket',],axis=1)
#x_train.head()

In [5]:
x_train.dtypes

Pclass        int64
Name            str
Sex             str
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin           str
Embarked        str
dtype: object

### Clean Dataset Check

In [6]:
check_empties = []
for column in x_train.columns:
    tmp_list = [column, int(np.sum(x_train[column].isna()))]
    #print(column)
    #print(np.sum(x_train[column].isna()))
    check_empties.append(tmp_list)
print(check_empties)

[['Pclass', 0], ['Name', 0], ['Sex', 0], ['Age', 177], ['SibSp', 0], ['Parch', 0], ['Fare', 0], ['Cabin', 687], ['Embarked', 2]]

In [7]:
category = 'Name'
for value in zip(x_train[category],x_train[category].isna()):
    print(value)
#print(enumerate(x_train['Cabin'].isna())

('Braund, Mr. Owen Harris', False)
('Cumings, Mrs. John Bradley (Florence Briggs Thayer)', False)
('Heikkinen, Miss. Laina', False)
('Futrelle, Mrs. Jacques Heath (Lily May Peel)', False)
('Allen, Mr. William Henry', False)
('Moran, Mr. James', False)
('McCarthy, Mr. Timothy J', False)
('Palsson, Master. Gosta Leonard', False)
('Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', False)
('Nasser, Mrs. Nicholas (Adele Achem)', False)
('Sandstrom, Miss. Marguerite Rut', False)
('Bonnell, Miss. Elizabeth', False)
('Saundercock, Mr. William Henry', False)
('Andersson, Mr. Anders Johan', False)
('Vestrom, Miss. Hulda Amanda Adolfina', False)
('Hewlett, Mrs. (Mary D Kingcome) ', False)
('Rice, Master. Eugene', False)
('Williams, Mr. Charles Eugene', False)
('Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', False)
('Masselmani, Mrs. Fatima', False)
('Fynney, Mr. Joseph J', False)
('Beesley, Mr. Lawrence', False)
('McGowan, Miss. Anna "Annie"', False)
('Sloper, Mr. William Thompson', False)
('Palsson, Miss. Torborg Danira', False)
('Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', False)
('Emir, Mr. Farred Chehab', False)
('Fortune, Mr. Charles Alexander', False)
('O\'Dwyer, Miss. Ellen "Nellie"', False)
('Todoroff, Mr. Lalio', False)
('Uruchurtu, Don. Manuel E', False)
('Spencer, Mrs. William Augustus (Marie Eugenie)', False)
('Glynn, Miss. Mary Agatha', False)
('Wheadon, Mr. Edward H', False)
('Meyer, Mr. Edgar Joseph', False)
('Holverson, Mr. Alexander Oskar', False)
('Mamee, Mr. Hanna', False)
('Cann, Mr. Ernest Charles', False)
('Vander Planke, Miss. Augusta Maria', False)
('Nicola-Yarred, Miss. Jamila', False)
('Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', False)
('Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', False)
('Kraeff, Mr. Theodor', False)
('Laroche, Miss. Simonne Marie Anne Andree', False)
('Devaney, Miss. Margaret Delia', False)
('Rogers, Mr. William John', False)
('Lennon, Mr. Denis', False)
("O'Driscoll, Miss. Bridget", False)
('Samaan, Mr. Youssef', False)
('Arnold-Franchi, Mrs. Josef (Josefine Franchi)', False)
('Panula, Master. Juha Niilo', False)
('Nosworthy, Mr. Richard Cater', False)
('Harper, Mrs. Henry Sleeper (Myna Haxtun)', False)
('Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', False)
('Ostby, Mr. Engelhart Cornelius', False)
('Woolner, Mr. Hugh', False)
('Rugg, Miss. Emily', False)
('Novel, Mr. Mansouer', False)
('West, Miss. Constance Mirium', False)
('Goodwin, Master. William Frederick', False)
('Sirayanian, Mr. Orsen', False)
('Icard, Miss. Amelie', False)
('Harris, Mr. Henry Birkhardt', False)
('Skoog, Master. Harald', False)
('Stewart, Mr. Albert A', False)
('Moubarek, Master. Gerios', False)
('Nye, Mrs. (Elizabeth Ramell)', False)
('Crease, Mr. Ernest James', False)
('Andersson, Miss. Erna Alexandra', False)
('Kink, Mr. Vincenz', False)
('Jenkin, Mr. Stephen Curnow', False)
('Goodwin, Miss. Lillian Amy', False)
('Hood, Mr. Ambrose Jr', False)
('Chronopoulos, Mr. Apostolos', False)
('Bing, Mr. Lee', False)
('Moen, Mr. Sigurd Hansen', False)
('Staneff, Mr. Ivan', False)
('Moutal, Mr. Rahamin Haim', False)
('Caldwell, Master. Alden Gates', False)
('Dowdell, Miss. Elizabeth', False)
('Waelens, Mr. Achille', False)
('Sheerlinck, Mr. Jan Baptist', False)
('McDermott, Miss. Brigdet Delia', False)
('Carrau, Mr. Francisco M', False)
('Ilett, Miss. Bertha', False)
('Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', False)
('Ford, Mr. William Neal', False)
('Slocovski, Mr. Selman Francis', False)
('Fortune, Miss. Mabel Helen', False)
('Celotti, Mr. Francesco', False)
('Christmann, Mr. Emil', False)
('Andreasson, Mr. Paul Edvin', False)
('Chaffee, Mr. Herbert Fuller', False)
('Dean, Mr. Bertram Frank', False)
('Coxon, Mr. Daniel', False)
('Shorney, Mr. Charles Joseph', False)
('Goldschmidt, Mr. George B', False)
('Greenfield, Mr. William Bertram', False)
('Doling, Mrs. John T (Ada Julia Bone)', False)
('Kantor, Mr. Sinai', False)
('Petranec, Miss. Matilda', False)
('Petroff, Mr. Pastcho ("Pentcho")', False)
('White, Mr. Richard Frasar', False)
('Johansson, Mr. Gustaf Joel', False)
('Gustafsson, Mr. Anders Vilhelm', False)
('Mionoff, Mr. Stoytcho', False)
('Salkjelsvik, Miss. Anna Kristine', False)
('Moss, Mr. Albert Johan', False)
('Rekic, Mr. Tido', False)
('Moran, Miss. Bertha', False)
('Porter, Mr. Walter Chamberlain', False)
('Zabour, Miss. Hileni', False)
('Barton, Mr. David John', False)
('Jussila, Miss. Katriina', False)
('Attalah, Miss. Malake', False)
('Pekoniemi, Mr. Edvard', False)
('Connors, Mr. Patrick', False)
('Turpin, Mr. William John Robert', False)
('Baxter, Mr. Quigg Edmond', False)
('Andersson, Miss. Ellis Anna Maria', False)
('Hickman, Mr. Stanley George', False)
('Moore, Mr. Leonard Charles', False)
('Nasser, Mr. Nicholas', False)
('Webber, Miss. Susan', False)
('White, Mr. Percival Wayland', False)
('Nicola-Yarred, Master. Elias', False)
('McMahon, Mr. Martin', False)
('Madsen, Mr. Fridtjof Arne', False)
('Peter, Miss. Anna', False)
('Ekstrom, Mr. Johan', False)
('Drazenoic, Mr. Jozef', False)
('Coelho, Mr. Domingos Fernandeo', False)
('Robins, Mrs. Alexander A (Grace Charity Laury)', False)
('Weisz, Mrs. Leopold (Mathilde Francoise Pede)', False)
('Sobey, Mr. Samuel James Hayden', False)
('Richard, Mr. Emile', False)
('Newsom, Miss. Helen Monypeny', False)
('Futrelle, Mr. Jacques Heath', False)
('Osen, Mr. Olaf Elon', False)
('Giglio, Mr. Victor', False)
('Boulos, Mrs. Joseph (Sultana)', False)
('Nysten, Miss. Anna Sofia', False)
('Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', False)
('Burke, Mr. Jeremiah', False)
('Andrew, Mr. Edgardo Samuel', False)
('Nicholls, Mr. Joseph Charles', False)
('Andersson, Mr. August Edvard ("Wennerstrom")', False)
('Ford, Miss. Robina Maggie "Ruby"', False)
('Navratil, Mr. Michel ("Louis M Hoffman")', False)
('Byles, Rev. Thomas Roussel Davids', False)
('Bateman, Rev. Robert James', False)
('Pears, Mrs. Thomas (Edith Wearne)', False)
('Meo, Mr. Alfonzo', False)
('van Billiard, Mr. Austin Blyler', False)
('Olsen, Mr. Ole Martin', False)
('Williams, Mr. Charles Duane', False)
('Gilnagh, Miss. Katherine "Katie"', False)
('Corn, Mr. Harry', False)
('Smiljanic, Mr. Mile', False)
('Sage, Master. Thomas Henry', False)
('Cribb, Mr. John Hatfield', False)
('Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', False)
('Bengtsson, Mr. John Viktor', False)
('Calic, Mr. Jovo', False)
('Panula, Master. Eino Viljami', False)
('Goldsmith, Master. Frank John William "Frankie"', False)
('Chibnall, Mrs. (Edith Martha Bowerman)', False)
('Skoog, Mrs. William (Anna Bernhardina Karlsson)', False)
('Baumann, Mr. John D', False)
('Ling, Mr. Lee', False)
('Van der hoef, Mr. Wyckoff', False)
('Rice, Master. Arthur', False)
('Johnson, Miss. Eleanor Ileen', False)
('Sivola, Mr. Antti Wilhelm', False)
('Smith, Mr. James Clinch', False)
('Klasen, Mr. Klas Albin', False)
('Lefebre, Master. Henry Forbes', False)
('Isham, Miss. Ann Elizabeth', False)
('Hale, Mr. Reginald', False)
('Leonard, Mr. Lionel', False)
('Sage, Miss. Constance Gladys', False)
('Pernot, Mr. Rene', False)
('Asplund, Master. Clarence Gustaf Hugo', False)
('Becker, Master. Richard F', False)
('Kink-Heilmann, Miss. Luise Gretchen', False)
('Rood, Mr. Hugh Roscoe', False)
('O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', False)
('Romaine, Mr. Charles Hallace ("Mr C Rolmane")', False)
('Bourke, Mr. John', False)
('Turcin, Mr. Stjepan', False)
('Pinsky, Mrs. (Rosa)', False)
('Carbines, Mr. William', False)
('Andersen-Jensen, Miss. Carla Christine Nielsine', False)
('Navratil, Master. Michel M', False)
('Brown, Mrs. James Joseph (Margaret Tobin)', False)
('Lurette, Miss. Elise', False)
('Mernagh, Mr. Robert', False)
('Olsen, Mr. Karl Siegwart Andreas', False)
('Madigan, Miss. Margaret "Maggie"', False)
('Yrois, Miss. Henriette ("Mrs Harbeck")', False)
('Vande Walle, Mr. Nestor Cyriel', False)
('Sage, Mr. Frederick', False)
('Johanson, Mr. Jakob Alfred', False)
('Youseff, Mr. Gerious', False)
('Cohen, Mr. Gurshon "Gus"', False)
('Strom, Miss. Telma Matilda', False)
('Backstrom, Mr. Karl Alfred', False)
('Albimona, Mr. Nassef Cassem', False)
('Carr, Miss. Helen "Ellen"', False)
('Blank, Mr. Henry', False)
('Ali, Mr. Ahmed', False)
('Cameron, Miss. Clear Annie', False)
('Perkin, Mr. John Henry', False)
('Givard, Mr. Hans Kristensen', False)
('Kiernan, Mr. Philip', False)
('Newell, Miss. Madeleine', False)
('Honkanen, Miss. Eliina', False)
('Jacobsohn, Mr. Sidney Samuel', False)
('Bazzani, Miss. Albina', False)
('Harris, Mr. Walter', False)
('Sunderland, Mr. Victor Francis', False)
('Bracken, Mr. James H', False)
('Green, Mr. George Henry', False)
('Nenkoff, Mr. Christo', False)
('Hoyt, Mr. Frederick Maxfield', False)
('Berglund, Mr. Karl Ivar Sven', False)
('Mellors, Mr. William John', False)
('Lovell, Mr. John Hall ("Henry")', False)
('Fahlstrom, Mr. Arne Jonas', False)
('Lefebre, Miss. Mathilde', False)
('Harris, Mrs. Henry Birkhardt (Irene Wallach)', False)
('Larsson, Mr. Bengt Edvin', False)
('Sjostedt, Mr. Ernst Adolf', False)
('Asplund, Miss. Lillian Gertrud', False)
('Leyson, Mr. Robert William Norman', False)
('Harknett, Miss. Alice Phoebe', False)
('Hold, Mr. Stephen', False)
('Collyer, Miss. Marjorie "Lottie"', False)
('Pengelly, Mr. Frederick William', False)
('Hunt, Mr. George Henry', False)
('Zabour, Miss. Thamine', False)
('Murphy, Miss. Katherine "Kate"', False)
('Coleridge, Mr. Reginald Charles', False)
('Maenpaa, Mr. Matti Alexanteri', False)
('Attalah, Mr. Sleiman', False)
('Minahan, Dr. William Edward', False)
('Lindahl, Miss. Agda Thorilda Viktoria', False)
('Hamalainen, Mrs. William (Anna)', False)
('Beckwith, Mr. Richard Leonard', False)
('Carter, Rev. Ernest Courtenay', False)
('Reed, Mr. James George', False)
('Strom, Mrs. Wilhelm (Elna Matilda Persson)', False)
('Stead, Mr. William Thomas', False)
('Lobb, Mr. William Arthur', False)
('Rosblom, Mrs. Viktor (Helena Wilhelmina)', False)
('Touma, Mrs. Darwis (Hanne Youssef Razi)', False)
('Thorne, Mrs. Gertrude Maybelle', False)
('Cherry, Miss. Gladys', False)
('Ward, Miss. Anna', False)
('Parrish, Mrs. (Lutie Davis)', False)
('Smith, Mr. Thomas', False)
('Asplund, Master. Edvin Rojj Felix', False)
('Taussig, Mr. Emil', False)
('Harrison, Mr. William', False)
('Henry, Miss. Delia', False)
('Reeves, Mr. David', False)
('Panula, Mr. Ernesti Arvid', False)
('Persson, Mr. Ernst Ulrik', False)
('Graham, Mrs. William Thompson (Edith Junkins)', False)
('Bissette, Miss. Amelia', False)
('Cairns, Mr. Alexander', False)
('Tornquist, Mr. William Henry', False)
('Mellinger, Mrs. (Elizabeth Anne Maidment)', False)
('Natsch, Mr. Charles H', False)
('Healy, Miss. Hanora "Nora"', False)
('Andrews, Miss. Kornelia Theodosia', False)
('Lindblom, Miss. Augusta Charlotta', False)
('Parkes, Mr. Francis "Frank"', False)
('Rice, Master. Eric', False)
('Abbott, Mrs. Stanton (Rosa Hunt)', False)
('Duane, Mr. Frank', False)
('Olsson, Mr. Nils Johan Goransson', False)
('de Pelsmaeker, Mr. Alfons', False)
('Dorking, Mr. Edward Arthur', False)
('Smith, Mr. Richard William', False)
('Stankovic, Mr. Ivan', False)
('de Mulder, Mr. Theodore', False)
('Naidenoff, Mr. Penko', False)
('Hosono, Mr. Masabumi', False)
('Connolly, Miss. Kate', False)
('Barber, Miss. Ellen "Nellie"', False)
('Bishop, Mrs. Dickinson H (Helen Walton)', False)
('Levy, Mr. Rene Jacques', False)
('Haas, Miss. Aloisia', False)
('Mineff, Mr. Ivan', False)
('Lewy, Mr. Ervin G', False)
('Hanna, Mr. Mansour', False)
('Allison, Miss. Helen Loraine', False)
('Saalfeld, Mr. Adolphe', False)
('Baxter, Mrs. James (Helene DeLaudeniere Chaput)', False)
('Kelly, Miss. Anna Katherine "Annie Kate"', False)
('McCoy, Mr. Bernard', False)
('Johnson, Mr. William Cahoone Jr', False)
('Keane, Miss. Nora A', False)
('Williams, Mr. Howard Hugh "Harry"', False)
('Allison, Master. Hudson Trevor', False)
('Fleming, Miss. Margaret', False)
('Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)', False)
('Abelson, Mr. Samuel', False)
('Francatelli, Miss. Laura Mabel', False)
('Hays, Miss. Margaret Bechstein', False)
('Ryerson, Miss. Emily Borie', False)
('Lahtinen, Mrs. William (Anna Sylfven)', False)
('Hendekovic, Mr. Ignjac', False)
('Hart, Mr. Benjamin', False)
('Nilsson, Miss. Helmina Josefina', False)
('Kantor, Mrs. Sinai (Miriam Sternin)', False)
('Moraweck, Dr. Ernest', False)
('Wick, Miss. Mary Natalie', False)
('Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)', False)
('Dennis, Mr. Samuel', False)
('Danoff, Mr. Yoto', False)
('Slayter, Miss. Hilda Mary', False)
('Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)', False)
('Sage, Mr. George John Jr', False)
('Young, Miss. Marie Grice', False)
('Nysveen, Mr. Johan Hansen', False)
('Ball, Mrs. (Ada E Hall)', False)
('Goldsmith, Mrs. Frank John (Emily Alice Brown)', False)
('Hippach, Miss. Jean Gertrude', False)
('McCoy, Miss. Agnes', False)
('Partner, Mr. Austen', False)
('Graham, Mr. George Edward', False)
('Vander Planke, Mr. Leo Edmondus', False)
('Frauenthal, Mrs. Henry William (Clara Heinsheimer)', False)
('Denkoff, Mr. Mitto', False)
('Pears, Mr. Thomas Clinton', False)
('Burns, Miss. Elizabeth Margaret', False)
('Dahl, Mr. Karl Edwart', False)
('Blackwell, Mr. Stephen Weart', False)
('Navratil, Master. Edmond Roger', False)
('Fortune, Miss. Alice Elizabeth', False)
('Collander, Mr. Erik Gustaf', False)
('Sedgwick, Mr. Charles Frederick Waddington', False)
('Fox, Mr. Stanley Hubert', False)
('Brown, Miss. Amelia "Mildred"', False)
('Smith, Miss. Marion Elsie', False)
('Davison, Mrs. Thomas Henry (Mary E Finck)', False)
('Coutts, Master. William Loch "William"', False)
('Dimic, Mr. Jovan', False)
('Odahl, Mr. Nils Martin', False)
('Williams-Lambert, Mr. Fletcher Fellows', False)
('Elias, Mr. Tannous', False)
('Arnold-Franchi, Mr. Josef', False)
('Yousif, Mr. Wazli', False)
('Vanden Steen, Mr. Leo Peter', False)
('Bowerman, Miss. Elsie Edith', False)
('Funk, Miss. Annie Clemmer', False)
('McGovern, Miss. Mary', False)
('Mockler, Miss. Helen Mary "Ellie"', False)
('Skoog, Mr. Wilhelm', False)
('del Carlo, Mr. Sebastiano', False)
('Barbara, Mrs. (Catherine David)', False)
('Asim, Mr. Adola', False)
("O'Brien, Mr. Thomas", False)
('Adahl, Mr. Mauritz Nils Martin', False)
('Warren, Mrs. Frank Manley (Anna Sophia Atkinson)', False)
('Moussa, Mrs. (Mantoura Boulos)', False)
('Jermyn, Miss. Annie', False)
('Aubart, Mme. Leontine Pauline', False)
('Harder, Mr. George Achilles', False)
('Wiklund, Mr. Jakob Alfred', False)
('Beavan, Mr. William Thomas', False)
('Ringhini, Mr. Sante', False)
('Palsson, Miss. Stina Viola', False)
('Meyer, Mrs. Edgar Joseph (Leila Saks)', False)
('Landergren, Miss. Aurora Adelia', False)
('Widener, Mr. Harry Elkins', False)
('Betros, Mr. Tannous', False)
('Gustafsson, Mr. Karl Gideon', False)
('Bidois, Miss. Rosalie', False)
('Nakid, Miss. Maria ("Mary")', False)
('Tikkanen, Mr. Juho', False)
('Holverson, Mrs. Alexander Oskar (Mary Aline Towner)', False)
('Plotcharsky, Mr. Vasil', False)
('Davies, Mr. Charles Henry', False)
('Goodwin, Master. Sidney Leonard', False)
('Buss, Miss. Kate', False)
('Sadlier, Mr. Matthew', False)
('Lehmann, Miss. Bertha', False)
('Carter, Mr. William Ernest', False)
('Jansson, Mr. Carl Olof', False)
('Gustafsson, Mr. Johan Birger', False)
('Newell, Miss. Marjorie', False)
('Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)', False)
('Johansson, Mr. Erik', False)
('Olsson, Miss. Elina', False)
('McKane, Mr. Peter David', False)
('Pain, Dr. Alfred', False)
('Trout, Mrs. William H (Jessie L)', False)
('Niskanen, Mr. Juha', False)
('Adams, Mr. John', False)
('Jussila, Miss. Mari Aina', False)
('Hakkarainen, Mr. Pekka Pietari', False)
('Oreskovic, Miss. Marija', False)
('Gale, Mr. Shadrach', False)
('Widegren, Mr. Carl/Charles Peter', False)
('Richards, Master. William Rowe', False)
('Birkeland, Mr. Hans Martin Monsen', False)
('Lefebre, Miss. Ida', False)
('Sdycoff, Mr. Todor', False)
('Hart, Mr. Henry', False)
('Minahan, Miss. Daisy E', False)
('Cunningham, Mr. Alfred Fleming', False)
('Sundman, Mr. Johan Julian', False)
('Meek, Mrs. Thomas (Annie Louise Rowley)', False)
('Drew, Mrs. James Vivian (Lulu Thorne Christian)', False)
('Silven, Miss. Lyyli Karoliina', False)
('Matthews, Mr. William John', False)
('Van Impe, Miss. Catharina', False)
('Gheorgheff, Mr. Stanio', False)
('Charters, Mr. David', False)
('Zimmerman, Mr. Leo', False)
('Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)', False)
('Rosblom, Mr. Viktor Richard', False)
('Wiseman, Mr. Phillippe', False)
('Clarke, Mrs. Charles V (Ada Maria Winfield)', False)
('Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")', False)
('Flynn, Mr. James', False)
('Pickard, Mr. Berk (Berk Trembisky)', False)
('Bjornstrom-Steffansson, Mr. Mauritz Hakan', False)
('Thorneycroft, Mrs. Percival (Florence Kate White)', False)
('Louch, Mrs. Charles Alexander (Alice Adelaide Slow)', False)
('Kallio, Mr. Nikolai Erland', False)
('Silvey, Mr. William Baird', False)
('Carter, Miss. Lucile Polk', False)
('Ford, Miss. Doolina Margaret "Daisy"', False)
('Richards, Mrs. Sidney (Emily Hocking)', False)
('Fortune, Mr. Mark', False)
('Kvillner, Mr. Johan Henrik Johannesson', False)
('Hart, Mrs. Benjamin (Esther Ada Bloomfield)', False)
('Hampe, Mr. Leon', False)
('Petterson, Mr. Johan Emil', False)
('Reynaldo, Ms. Encarnacion', False)
('Johannesen-Bratthammer, Mr. Bernt', False)
('Dodge, Master. Washington', False)
('Mellinger, Miss. Madeleine Violet', False)
('Seward, Mr. Frederic Kimber', False)
('Baclini, Miss. Marie Catherine', False)
('Peuchen, Major. Arthur Godfrey', False)
('West, Mr. Edwy Arthur', False)
('Hagland, Mr. Ingvald Olai Olsen', False)
('Foreman, Mr. Benjamin Laventall', False)
('Goldenberg, Mr. Samuel L', False)
('Peduzzi, Mr. Joseph', False)
('Jalsevac, Mr. Ivan', False)
('Millet, Mr. Francis Davis', False)
('Kenyon, Mrs. Frederick R (Marion)', False)
('Toomey, Miss. Ellen', False)
("O'Connor, Mr. Maurice", False)
('Anderson, Mr. Harry', False)
('Morley, Mr. William', False)
('Gee, Mr. Arthur H', False)
('Milling, Mr. Jacob Christian', False)
('Maisner, Mr. Simon', False)
('Goncalves, Mr. Manuel Estanslas', False)
('Campbell, Mr. William', False)
('Smart, Mr. John Montgomery', False)
('Scanlan, Mr. James', False)
('Baclini, Miss. Helene Barbara', False)
('Keefe, Mr. Arthur', False)
('Cacic, Mr. Luka', False)
('West, Mrs. Edwy Arthur (Ada Mary Worth)', False)
('Jerwan, Mrs. Amin S (Marie Marthe Thuillard)', False)
('Strandberg, Miss. Ida Sofia', False)
('Clifford, Mr. George Quincy', False)
('Renouf, Mr. Peter Henry', False)
('Braund, Mr. Lewis Richard', False)
('Karlsson, Mr. Nils August', False)
('Hirvonen, Miss. Hildur E', False)
('Goodwin, Master. Harold Victor', False)
('Frost, Mr. Anthony Wood "Archie"', False)
('Rouse, Mr. Richard Henry', False)
('Turkula, Mrs. (Hedwig)', False)
('Bishop, Mr. Dickinson H', False)
('Lefebre, Miss. Jeannie', False)
('Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)', False)
('Kent, Mr. Edward Austin', False)
('Somerton, Mr. Francis William', False)
('Coutts, Master. Eden Leslie "Neville"', False)
('Hagland, Mr. Konrad Mathias Reiersen', False)
('Windelov, Mr. Einar', False)
('Molson, Mr. Harry Markland', False)
('Artagaveytia, Mr. Ramon', False)
('Stanley, Mr. Edward Roland', False)
('Yousseff, Mr. Gerious', False)
('Eustis, Miss. Elizabeth Mussey', False)
('Shellard, Mr. Frederick William', False)
('Allison, Mrs. Hudson J C (Bessie Waldo Daniels)', False)
('Svensson, Mr. Olof', False)
('Calic, Mr. Petar', False)
('Canavan, Miss. Mary', False)
("O'Sullivan, Miss. Bridget Mary", False)
('Laitinen, Miss. Kristina Sofia', False)
('Maioni, Miss. Roberta', False)
('Penasco y Castellana, Mr. Victor de Satode', False)
('Quick, Mrs. Frederick Charles (Jane Richards)', False)
('Bradley, Mr. George ("George Arthur Brayton")', False)
('Olsen, Mr. Henry Margido', False)
('Lang, Mr. Fang', False)

### Imputing Values Required?

#### Imputing Age

In [8]:
# Impute missing age values as median of Name title (Mr. Mrs. Ms. ...), Pclass (1, 2, 3), and Sex (Male, Female)

In [9]:
# Find all titles: Assume title starts after ", " and ends after ".", no missing names in dataset

# Strip all names down to title/honorific using regex
Titles = []
for name in x_train['Name']: # For all names in the dataset
    match = re.search(", .*?\\. ",name).group() # The part of the string that matches our conditions to start at ', ' and end at '. '
    Titles.append(match.lstrip(', ').rstrip(' ')) # Append the honorific stripped of prefix/suffix

UTitles = set(Titles) # All unique titles
print(len(UTitles)," unique titles / honorifics")
print(UTitles)

17  unique titles / honorifics
{'Rev.', 'Sir.', 'Master.', 'Dr.', 'Mr.', 'Ms.', 'the Countess.', 'Capt.', 'Don.', 'Miss.', 'Major.', 'Lady.', 'Jonkheer.', 'Mme.', 'Mlle.', 'Col.', 'Mrs.'}

In [10]:
# Imputes age values by sex, social status, then by title/honorific
unique_titles = x_train['Name'].str.extract(f"({'|'.join(UTitles)})", expand=False) # Searching for any titles in the unique list

x_train['Age'] = x_train['Age'].fillna(x_train.groupby(['Sex', 'Pclass', unique_titles])['Age'].transform('median'))

In [11]:
# If no other examples within sex/social status/title exist, impute with global median
global_median = x_train['Age'].median()
x_train['Age'] = x_train['Age'].fillna(global_median)

#### Imputing Cabin (removing numeric vals, keeping alpha designation)

In [12]:
# Not implemented yet

### Encoding Required?

In [13]:
x_train = x_train.drop(columns=['Name','Cabin'])

In [14]:
x_train.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [24]:
# Encode sex with pd dummies

# Imputing embarked categorical with most often occuring value, no missing values for sex (excluded)
x_train['Embarked'] = x_train['Embarked'].fillna(x_train['Embarked'].mode()[0]) 

# Convert cleans categoricals to OHE cols
x_train_encoded = pd.get_dummies(x_train, columns=['Embarked','Sex'], drop_first=True)

# Convert T/F to 1/0
x_train_encoded = x_train_encoded.astype(float)

In [25]:
# Depends on the model used, not for RF/XGB
# Converting string columns to categories
# Use OHE

#x_train_encoded = pd.get_dummies(x_train,drop_first=True)

#for col in x_train.columns:
#    if (x_train[col].dtype == str) or (x_train[col].dtype == object):
#        print(col)
#        x_train[col] = x_train[col].astype('category')

### Train Test Split

In [26]:
# Not necessary, separate file given

### Shuffling Training Examples

In [27]:
x_train_encoded, y_train = sk.utils.shuffle(x_train_encoded,y_train,random_state=12)

In [28]:
x_train_encoded.head()

     Pclass   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S  Sex_male
456     1.0  65.0    0.0    0.0  26.5500         0.0         1.0       1.0
351     1.0  39.5    0.0    0.0  35.0000         0.0         1.0       1.0
173     3.0  21.0    0.0    0.0   7.9250         0.0         1.0       1.0
671     1.0  31.0    1.0    0.0  52.0000         0.0         1.0       1.0
836     3.0  21.0    0.0    0.0   8.6625         0.0         1.0       1.0

In [29]:
y_train.head() # checking if examples still ordered wrt x_train_shuff; verified

886    0
13     0
97     1
410    0
577    1
Name: Survived, dtype: int64

### Imputing Values if Required

## Model

### Model Setup

In [30]:
# Models used (Estimators dict / list)
# Use: Random Forest, XGBoost, LightGBM (Not the last one)
estimators = {
    #[name, model]
    'random_forest':   sk.ensemble.RandomForestClassifier(),
    'xgboost':         xgboost.XGBClassifier() 
    }

In [31]:
estimators.items()

dict_items([('random_forest', RandomForestClassifier()), ('xgboost', XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...))])

### Training

In [33]:
# model.fit(x_train,y_train)
models = {}

for model_name, model in estimators.items():
    #print(model_name)
    trained = model.fit(x_train_encoded,y_train)
    models[model_name] = trained
    trained = None
    #print(model)

### Initial Results

In [50]:
# Visualized; accuracy, PR Curves, AUC table summary
# model.predict(x_test)
# sklearn.metrics.score(y_train,y_test)

print("Where 0 represents an individual passenger's survival "
        "and 1 represents a single passenger not surviving:\n")

for model_name in models:
    y_pred = models[model_name].predict(x_train_encoded)
    class_rep = sk.metrics.classification_report(y_train,y_pred)
    print(f"Classification Report for {model_name.replace("_"," ").capitalize()} model:\n{class_rep}")
    accuracy = sk.metrics.accuracy_score(y_train, y_pred)
    #AUC = sk.metrics.auc(y_train,y_pred)

    #
    # print("Accuracy of",model_name,"model: ",accuracy)
    #print("AUC of",model_name,"model: ",AUC)

Where 0 represents an individual passenger's survival and 1 represents a single passenger not surviving:

Classification Report for Random forest model:
              precision    recall  f1-score   support

           0       0.94      0.95      0.95       549
           1       0.93      0.90      0.91       342

    accuracy                           0.93       891
   macro avg       0.93      0.93      0.93       891
weighted avg       0.93      0.93      0.93       891

Classification Report for Xgboost model:
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       549
           1       0.89      0.83      0.86       342

    accuracy                           0.90       891
   macro avg       0.90      0.88      0.89       891
weighted avg       0.90      0.90      0.90       891

## Optimization

### Optuna Objective

### Train & Validation Sets

### Optimize Against Validation Set

### Perfomance Versus Unoptimized

### Results